# Generated by Django 6.0.3 on 2026-03-16 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(max_length=500)),
                ('entreprise', models.CharField(blank=True, max_length=300, null=True)),
                ('ville', models.CharField(blank=True, max_length=100, null=True)),
                ('type_contrat', models.CharField(blank=True, max_length=100, null=True)),
                ('date_publication', models.DateField(blank=True, null=True)),
                ('competences', models.TextField(blank=True, null=True)),
                ('secteur', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Offre',
                'verbose_name_plural': 'Offres',
                'ordering': ['-date_publication'],
            },
        ),
    ]
